{{- $fullName := include "affine.fullname" . -}}
{{- $isPersistence := .Values.persistence.enabled -}}
{{- $existingClaim := .Values.persistence.existingClaim -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "affine.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ $fullName }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "affine.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        name: {{ $fullName }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - sh
            - -c
            - node ./scripts/self-host-predeploy && node ./dist/index.js
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $key, $val := .Values.ports }}
            - containerPort: {{ .containerPort | default "80" }}
              protocol: {{ .protocol | upper | default "TCP"}}
          {{- end }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.persistence.enabled .Values.volumeMounts}}
          volumeMounts:
          {{- if $isPersistence }}
            - mountPath: {{.Values.persistence.mountPath}}
              name: {{ $fullName}}-storage
          {{- end}}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end}}
      {{- if or .Values.persistence.enabled .Values.volumes}}
      volumes:
        {{- if $isPersistence}}
        - name: {{ $fullName}}-storage
          persistentVolumeClaim:
            claimName: {{ $existingClaim | default $fullName }}-pvc
        {{- end }}
        {{- with .Values.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
